name: Publish & Deploy Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (test or prod)'
        required: true
        default: 'test'

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8

      - name: Deploy to Dev Environment
        run: |
          mvn clean deploy -DmuleDeploy \
            -Denv.ENV=Dev \
            -Denv.TARGET=Cloudhub-US-East-2 \
            -Denv.APP_NAME=maven-demo-riddhi-dev \
            --settings .maven/settings.xml

  deploy-manual:
    name: Deploy to Test or Prod (Manual)
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8

      - name: Deploy to ${{ github.event.inputs.environment }} Environment
        run: |
          TARGET=$(echo ${{ github.event.inputs.environment }} | grep -iq prod && echo Cloudhub-US-East-2 || echo Cloudhub-US-East-2)
          APP_NAME=maven-demo-riddhi-${{ github.event.inputs.environment }}
          mvn clean deploy -DmuleDeploy \
            -Denv.ENV=${{ github.event.inputs.environment }} \
            -Denv.TARGET=$TARGET \
            -Denv.APP_NAME=$APP_NAME \
            --settings .maven/settings.xml
