name: Publish & Deploy Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (test or prod)'
        required: true
        default: 'test'

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8

      - name: Publish to Exchange
        run: mvn clean deploy --settings .maven/settings.xml

      - name: Deploy to Dev Environment
        run: mvn clean deploy -DmuleDeploy --settings .maven/settings.xml
        env:
          ENV: dev

  deploy-manual:
    name: Deploy to Test or Prod (Manual)
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8

      - name: Publish to Exchange
        run: mvn clean deploy --settings .maven/settings.xml

      - name: Deploy to ${{ github.event.inputs.environment }} Environment
        run: mvn clean deploy -DmuleDeploy --settings .maven/settings.xml
        env:
          ENV: ${{ github.event.inputs.environment }}
